### ISSUE TITLE
Available perturbations

### ISSUE THREAD

**Issue by cwwhh** [pratyushmaini/llm_dataset_inference#1]
Hello, I have read your article on "LLM Dataset Inference Did you train on my dataset?" and am attempting to reproduce the code. However, I encountered an error when trying to use data_creator.sh. Could you please provide some relevant file references to help me resolve the issue? Thank you.
![图片](https://github.com/pratyushmaini/llm_dataset_inference/assets/166807394/df69acfc-6930-416d-92d1-df4a28c848d4)

**Comment by pratyushmaini** [comment]
Hi currently, the Pile dataset has been taken https://the-eye.eu/public/AI/pile/readme.txt

I will upload a small subset of it on `huggingface` as soon as I confirm that it is okay to do so. Thank you for your patience.

**Comment by cwwhh** [comment]
Thank you!
